// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/emails": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/projects/:projectId": {
    params: {
      "projectId": string;
    };
  };
  "/stages": {
    params: {};
  };
  "/user/profile": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sign-in" | "/sign-up" | "/forgot-password" | "/reset-password" | "/verify-email" | "/dashboard" | "/emails" | "/projects" | "/projects/:projectId" | "/stages" | "/user/profile";
  };
  "routes/auth/auth-layout.tsx": {
    id: "routes/auth/auth-layout";
    page: "/" | "/sign-in" | "/sign-up" | "/forgot-password" | "/reset-password" | "/verify-email";
  };
  "routes/root/home.tsx": {
    id: "routes/root/home";
    page: "/";
  };
  "routes/auth/sign-in.tsx": {
    id: "routes/auth/sign-in";
    page: "/sign-in";
  };
  "routes/auth/sign-up.tsx": {
    id: "routes/auth/sign-up";
    page: "/sign-up";
  };
  "routes/auth/forgot-password.tsx": {
    id: "routes/auth/forgot-password";
    page: "/forgot-password";
  };
  "routes/auth/reset-password.tsx": {
    id: "routes/auth/reset-password";
    page: "/reset-password";
  };
  "routes/auth/verify-email.tsx": {
    id: "routes/auth/verify-email";
    page: "/verify-email";
  };
  "routes/dashboard/dashboard-layout.tsx": {
    id: "routes/dashboard/dashboard-layout";
    page: "/dashboard" | "/emails" | "/projects" | "/projects/:projectId" | "/stages";
  };
  "routes/dashboard/index.tsx": {
    id: "routes/dashboard/index";
    page: "/dashboard";
  };
  "routes/emails/index.tsx": {
    id: "routes/emails/index";
    page: "/emails";
  };
  "routes/projects/index.tsx": {
    id: "routes/projects/index";
    page: "/projects";
  };
  "routes/projects/$projectId.tsx": {
    id: "routes/projects/$projectId";
    page: "/projects/:projectId";
  };
  "routes/stages/index.tsx": {
    id: "routes/stages/index";
    page: "/stages";
  };
  "routes/user/user-layout.tsx": {
    id: "routes/user/user-layout";
    page: "/user/profile";
  };
  "routes/user/profile.tsx": {
    id: "routes/user/profile";
    page: "/user/profile";
  };
};